### ISSUE TITLE
SQL query to find existing pages finds shortcodes from other plugins

### ISSUE THREAD

**Issue by thirdender** [itthinx/affiliates#25]
A friend of mine installed another WordPress affiliate plugin that created a few pages with shortcodes like `[AffiliatesHome]`. The following SQL in [class-affiliates-settings-pages.php](https://github.com/itthinx/affiliates/blob/dc0e0f2bcc0c732fbb687572c80cd44488e02366/lib/core/class-affiliates-settings-pages.php#L85) finds these other affiliate shortcodes by accident:

    $posts = $wpdb->get_results( "SELECT ID FROM $wpdb->posts WHERE post_content LIKE '%[affiliates_%' AND post_status = 'publish'" );

The reason is that the underscore (`_`) character is a wildcard in SQL.

**Comment by proaktion** [comment]
Many thanks @thirdender , this has been fixed in 2.15.2
